export const copy = {
  appTitle: 'Images to PDF',
  uploadTitle: 'Select an image folder, ZIP file, or RAR file',
  uploadHint: 'You can also drag image files, ZIP files, or RAR files into this area.',
  folderButton: 'Folder',
  archiveButton: 'ZIP or RAR',
  summary: {
    source: 'Source',
    images: 'Images',
    size: 'Size',
    ignored: 'Ignored',
    emptySource: 'No source selected',
  },
  composition: {
    title: 'PDF layout',
    empty: 'No images loaded',
    estimated: (count) => `${count} pages estimated`,
    format: 'Output format',
    exact: 'Image fills the page',
    paper: 'Standard paper page',
    imagesPerPage: 'Images per page',
    exactGrid: 'Image layout',
    columns: 'Columns',
    rows: 'Rows',
    auto: 'Auto',
    gridHint: 'Controls how images are arranged on each page. If there are more images than cells, the layout expands to fit them.',
    pageSize: 'Paper size',
    orientation: 'Orientation',
    portrait: 'Portrait',
    landscape: 'Landscape',
    margin: (value) => `Margin: ${value}px`,
    gap: (value) => `Spacing: ${value}px`,
  },
  actions: {
    generate: 'Generate PDF',
    clear: 'Clear',
    preview: (name) => `Preview ${name}`,
    download: 'Download',
    close: 'Close',
  },
  selectedPage: {
    title: 'Selected page preview',
    loaded: (index) => `Page ${index}`,
    empty: 'Load images to preview the page layout.',
    placeholder: 'The selected page will appear here.',
  },
  preview: {
    title: 'All pages',
    loaded: 'Drag pages to change their order before generating the PDF.',
    empty: 'Load images to preview the PDF before generating it.',
    placeholder: 'PDF pages will appear here.',
    pageLabel: (index) => `Page ${index}`,
  },
  result: {
    title: 'PDF generated successfully',
    message: (name) => `${name} is ready to preview or download.`,
  },
  status: {
    readingArchive: 'Reading archive file',
    loaded: (count, ignoredText = '') => `${count} images loaded${ignoredText}`,
    loadedArchive: (count, ignoredText = '') => `${count} images loaded from archive${ignoredText}`,
    ignoredFiles: (count) => ` (${count} files ignored)`,
    processingPage: (page, total) => `Processing page ${page} of ${total}`,
    finishing: 'Finalizing PDF',
    ready: (count) => `PDF ready: ${count} pages`,
  },
  errors: {
    noImages: (formats) => `No compatible images were found. Supported formats: ${formats}.`,
    noSelection: 'Select an image folder, image files, a ZIP file, or a RAR file first.',
    archiveRead: 'The archive file could not be read.',
    convertImage: (name) => `The browser could not read "${name}". Convert that image to JPG or PNG and try again.`,
    pngConvert: 'The image could not be converted to PNG.',
    generatePdf: 'The PDF could not be generated.',
  },
};
